### PR TITLE
Fixed Issue #1

### LINKED ISSUE #1: JavaScript import statement nor require statement is working and DOM query returns null/undefined always
JavaScript import statement nor require statement is working and DOM query returns null/undefined always

branch: javaScript
file: index.js

even after using export in data.js and import in index.js is still not working 
"even though I have given syntax and file location correctly"

all elements using querySelector return undefined when accessing inner HTML. 
if I managed to get it using getElementsByClassName also changes are not reflected.

also, the append child is not working

jquery is also not working

### PR DESCRIPTION
**Pull request by anmol111pal**
Fixed #1 JavaScript import statement nor require statement is working and DOM query returns null/undefined always

### CODE REVIEW

**Comment by anmol111pal** [comment]
While using export-import, the Javascript files must be used as modules.

**Comment by anmol111pal** [comment]
> Fixed #1 JavaScript import statement nor require statement is working and DOM query returns null/undefined always

Kindly review iit & merge it.

**Comment by Anish-Karthik** [comment]
> > Fixed #1 JavaScript import statement nor require statement is working and DOM query returns null/undefined always
> 
> Kindly review iit & merge it.

the issue is not in the main branch it is in a branch named javaScript

so i can't merge it sorry ;(

**Comment by anmol111pal** [comment]
> > > Fixed #1 JavaScript import statement nor require statement is working and DOM query returns null/undefined always
> > 
> > 
> > Kindly review iit & merge it.
> 
> the issue is not in the main branch it is in a branch named javaScript
> 
> so i can't merge it sorry ;(

Okay, I will fix that as well

**Pull request closed without merging**
